# https://projecteuler.net/problem=2

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

function generateFiboUnder(bound::Int64)
    arr = [1, 2]
    len = 2
    while arr[len] <= bound
        push!(arr, arr[len - 1] + arr[len])
        len += 1
    end
    if last(arr) > bound return arr[1:len-1] end
    return arr
end

function oneModThree(topInd::Int64)
    return 2:3:(topInd)
end

function main(topNum::Int64)
    arr = generateFiboUnder(topNum)
    return sum(arr[oneModThree(length(arr))])
end
